services:
  dev:
    build:
      context: .
      target: production
    volumes:
        - ./:/code
        - ./data:/data
    environment:
      - KBC_DATADIR=./data
  test:
    build:
      context: .
      target: test
    volumes:
      - ./:/code
      - ./data:/data
    environment:
      - KBC_DATADIR=./data
